### ISSUE TITLE
SkyBox mirror problem

### ISSUE THREAD

**Issue by uzman** [Rajawali/RajawaliExamples#57]
Hi,
i am using your framework for panorama photos.
			getCurrentScene().setSkybox(R.drawable.posx3, R.drawable.negx3,
					R.drawable.posy3, R.drawable.negy3, R.drawable.posz3,
					R.drawable.negz3);

but it mirrors the images. i mean all the writings on the buildings (in photos) are reversed.

any help please?

**Comment by jwoolston** [comment]
This is not an issue for the examples repository. That said, this is what the cube map material does, its not just your images. Not sure if this is correct or not. Post the issue on the Rajawali repo and we can discuss it there.

**Comment by uzman** [comment]
you can see if it is correct or not what i say.
ok, i will post it to Rajawali.
