### ISSUE TITLE
onDrawFrame

### ISSUE THREAD

**Issue by Angie-Ie** [Rajawali/RajawaliExamples#70]
Hai, i need to add object 3d and texture in runtime. I see a lot of solution in rajawali github's issue, they update texture runtime in onDrawFrame. But i can find override onDrawFrame, how to create object 3d and texture runtime?

**Comment by jwoolston** [comment]
Rajawali has an asynchronous system for this. Define them on any thread you would like and add them to the scene just like you would in `initScene()`. Rajawali will take care of the rest. Also, this is a rajawali support issue so it should be posted to the Rajawali repository.
